### ISSUE TITLE
TestIntegrationClientLinkInfos fails with "operation not supported"

### ISSUE THREAD

**Issue by dswarbrick** [mdlayher/ethtool#11]
Test fails as follows on Ubuntu 22.10 (kernel 5.19) and Debian bookworm (kernel 6.0, as of writing):
```
=== RUN   TestIntegrationClientLinkInfos
    client_linux_integration_test.go:23: failed to fetch link infos: netlink receive: operation not supported
--- FAIL: TestIntegrationClientLinkInfos (0.00s)
```
A git bisect reveals that the test started failing from commit 07f2ecdc165a478e1c8d93e0d17201498ab3acf5 onwards.

This failing test is preventing the packaging of this project in Debian, and subsequently the updating of the prometheus-node-exporter package, whose version 1.5.0 depends on this module.

**Comment by mdlayher** [comment]
Should be fixed as of https://github.com/mdlayher/ethtool/commit/5605e9b8817d4b1f44bc8f95934a984ef3a5e831.

**Comment by dswarbrick** [comment]
Confirmed, test is now successfully skipped on kernels 5.19, 6.0.

Thanks for the quick resolution.
